/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrafficRouteImport } from './routes/traffic'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as CapabilitiesRouteImport } from './routes/capabilities'
import { Route as IndexRouteImport } from './routes/index'

const TrafficRoute = TrafficRouteImport.update({
  id: '/traffic',
  path: '/traffic',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilitiesRoute = CapabilitiesRouteImport.update({
  id: '/capabilities',
  path: '/capabilities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capabilities': typeof CapabilitiesRoute
  '/company': typeof CompanyRoute
  '/insights': typeof InsightsRoute
  '/results': typeof ResultsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/traffic': typeof TrafficRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capabilities': typeof CapabilitiesRoute
  '/company': typeof CompanyRoute
  '/insights': typeof InsightsRoute
  '/results': typeof ResultsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/traffic': typeof TrafficRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/capabilities': typeof CapabilitiesRoute
  '/company': typeof CompanyRoute
  '/insights': typeof InsightsRoute
  '/results': typeof ResultsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/traffic': typeof TrafficRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/capabilities'
    | '/company'
    | '/insights'
    | '/results'
    | '/sitemap.xml'
    | '/traffic'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/capabilities'
    | '/company'
    | '/insights'
    | '/results'
    | '/sitemap.xml'
    | '/traffic'
  id:
    | '__root__'
    | '/'
    | '/capabilities'
    | '/company'
    | '/insights'
    | '/results'
    | '/sitemap.xml'
    | '/traffic'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CapabilitiesRoute: typeof CapabilitiesRoute
  CompanyRoute: typeof CompanyRoute
  InsightsRoute: typeof InsightsRoute
  ResultsRoute: typeof ResultsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrafficRoute: typeof TrafficRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/traffic': {
      id: '/traffic'
      path: '/traffic'
      fullPath: '/traffic'
      preLoaderRoute: typeof TrafficRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capabilities': {
      id: '/capabilities'
      path: '/capabilities'
      fullPath: '/capabilities'
      preLoaderRoute: typeof CapabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CapabilitiesRoute: CapabilitiesRoute,
  CompanyRoute: CompanyRoute,
  InsightsRoute: InsightsRoute,
  ResultsRoute: ResultsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrafficRoute: TrafficRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
